---
title: "HealthyFood"
subtitle: "a food truck problem"
author: "Samuel Orso, Sacha Varone"
date: "`r Sys.Date()`"
output: 
 prettydoc::html_pretty:
  theme: architect
  highlight: github
  toc: true
  df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warnings = FALSE, message = FALSE)
```

## Presentation
_Goodfood_ sells three different menus: _Earth_, _Surprise_ and _BlueLake_. It uses four different types of ingredients to produce the menus: _Pasta_, _Rice_, _Vegetable_ and _Fish_. A key component for a succesful business is to have an appropriate stock management. In ordre to know the quantities for each type of menu that have to be prepared each week, historical data from a similar food truck is provided [here](https://cyberlearn.hes-so.ch/mod/resource/view.php?id=8943). The futur number of menus sold at HealthyFood is suppose to be similar.  

The historical data of Goodfood comprises twelve variables:    

* *day*: The dates in the format 'yyyy-mm-dd'.   
* *week_day*: The day of the week.   
* *max_temp*: The daily maximal temperature in degrees Celsius.   
* *min_temp*: The daily minimal temperature in degrees Celsius.   
* *rainfall*: The amount of rainfall recorded for the day in mm.   
* *wind*: Wind speed (km/hr) averaged over 20 minutes prior to noon.    
* *location*: Four different locations.   
* *passerby*: An estimation of the number of person who pass by the food truck in circa 50 meters around.   
* *revenue*: The daily total revenue in hundreds (for all menus/beverages).   
* *Surprise*: The amount of _Surprise_ menu sold.   
* *Earth*: The amount of _Earth_ menu sold.   
* *BlueLake*: The amount of _BlueLake_ menu sold.   

## Work process

Your project is spread into two parts:   

1. First Part: Training part   

     + Group: You build a group of 2 person for the first part of this work. You are requested to register your group members on [Cyberlearn](https://cyberlearn.hes-so.ch/mod/moodecgrpmanagement/view.php?id=731084) by latest the 06.10.2017 (module/Project reports/Groups composition)    
     + Work: You all access the same training dataset through [Cyberlearn](https://cyberlearn.hes-so.ch/course/view.php?id=8943). With your colleague, you work on the data and try to answer the questions written in the project presentation. No report is requested for this first part.            
     
2. Second Part: Report and Evaluation part    

     + Group: On the 15th of November, we constitute groups of 4 students, by mixing random groups of your class.  
     + Work: You receive a new set of data. These data are specific for your Group and differs from other Groups. With this new set of data you answer the questions written in the project presentation. You write a report of maximum 4 pages (meaning 2 sheets recto-verso) per course (statistics, management science). The deadline to submit your report is December 15th. In case of late submission, a penalty of -0.2/day will be automatically applied. If no report is submitted, the group will receive the grade 0.

## Questions for multivariate statistics part
Your goal is to build a multivariate regression model that leads to good prediction accuracy. Your report (max 4 pages) should be structured as follows: 

* Title: the title of your report and the names of the members of the group.   
* Abstract: a summary of your results and the method you employed (max 150 words).   
* Introduction: state your objective and summarize the problem at stake.    
* Results: you shall seperate your results into four subsections: Explanatory analysis, Model building, Model checking and Prediction.   
* Discussion: summarize the important findings and open the debate for future research.   

The result should contain the most relevant findings. For example, if two predictors are multicollinear, it may be worth illustrating it in the Explantory Analysis. While working, there might be several iterations between Model building and Model checking. You should be as succint as possible: give your initial and final models and why (on what basis) you included/modified/excluded some predictors. 


To help you construct the report, you should answer the following questions:    

1. Make an exploratory analysis of the dataset, in particular answer the questions:    

      + What are the predictors, what are the response variables? What is their nature (factors, numeric, ordinal, …)?
      + Do you think there are problems of outliers, multicollinearity, non-linearity?   
      
2. Perform a one-way ANOVA test of BlueLake per week_day. Give all the necessary details (testing hypothesis, conclusion). Perform a multiple pairwise comparison. Repeat for the two other menus.    
3. Based on previous points, what regression model would you like to fit to explain the quantities of menus sold? Would you transform variables? Make a robust regression? Other? Write down the regression models you intend to fit.    
4. Based on your answer at point 3, fit three regression models, one per menu. Write down the estimated regression equations.    
5. Analyse the residuals of your regressions. Are the assumptions met? Would you make any modifications to the proposed model at point 3?    
6. Construct the full model for each menu: add potential non-linearities, take into account potential sources heteroscedasticity, outliers.
7. Select the 'best' model according to the AIC. Which model is it? Does it make sense to you? Do you believe some predictors are missing?     
8. Check your 'best' model. Do the assumptions of your multivariate linear regression hold? Discuss each assumption.   
9. Based on your 'best' model and the dataset `goodfood_test.csv`, construct the prediction interval for the three menus.   
