---
title: "Multivariate statistics"
subtitle: "Homeworks"
author: "Samuel Orso"
date: "`r Sys.Date()`"
output: 
 prettydoc::html_pretty:
  theme: architect
  highlight: github
  toc: true
  df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Introduction: Multivariate regression
<div id="ex1">
**Exercise 1:** You receive the data on the *Height* and *Weight* of some women aged between 30 to 39
1. Load the data in `R` using the command `data(women)`. (The dataset is also available in *.csv on (on [cyberlearn](https://cyberlearn.hes-so.ch/mod/folder/view.php?id=721591))).      
2. Read the description of this dataset by running the command `?women`.   
3. Using the commands seen in the course, plot the *Height* against the *Weight*.   
4. You are interested in explaining the *Weight* by the *Height*. Write the regression equation.   
5. Fit a regression model using the `lm(.)` function.   
6. From the `summary(.)` of this linear regression, write the estimated model.   
7. Suppose you observe a new women who measures 1.73 meters, predict her *Weight*.  
(For the last point, you may want to use the `grid` package).

You will find the correction [here](https://samorso.github.io/RM2017/hmw_cor.html#ex1)
</div>

# Descriptive analysis
<div id=ex2>
**Exercise 2:** Use the `ski.csv` dataset available on  [cyberlearn](https://cyberlearn.hes-so.ch/mod/folder/view.php?id=721591).  
1. Load the dataset in `R`. First set the working directory (where you want to work with `R` in your computer) by using the `setwd("my directory")` commands. Then load the dataset using the command `ski <- read.csv(file="ski.csv", header=TRUE, sep=";")`.   
2. Produce multiple boxplots.   
3. Produce a scatterplot and add the regression line and confidence interval (use the code of **Example 1** in the Introduction).   
4. Compute the linear and Spearman's correlations. Is there any outliers effect on the correlation?   
5. Fit the linear regression of *Tickets* explaines by *Temperature*.   
6. Write the estimated regression equation.   
7. With this model, predict the number of tickets that will be sold for a temperature of -2.5 degrees.   

You will find the correction [here](https://samorso.github.io/RM2017/hmw_cor.html#ex2)
</div>

# Inference
<div id="ex3">
**Exercise 3:** In motherhood, waiting times between the birth and the exit of 44 mothers were measured. Use the `hosptial.csv` dataset available on  [cyberlearn](https://cyberlearn.hes-so.ch/mod/folder/view.php?id=721591).  
1. Load the dataset in `R`. First set the working directory (where you want to work with `R` in your computer) by using the `setwd("my directory")` commands. Then load the dataset using the command `hospital <- read.csv(file="hospital.csv", header=TRUE, sep=";")`.   
2. Construct a confidence interval at a confidence level of 95\% for the average waiting time assuming the standard deviation is 1.   
3. Same as 2, but with an estimate of the standard deviation.  
4. Restart points 2 and 3 with a confidence level at 90\%, but before, do you expect the confidence intervals will be shorter or longer?  

You will find the correction [here](https://samorso.github.io/RM2017/hmw_cor.html#ex3)
</div>

<div id="ex4">
**Exercise 4:** Repeat (if possible) the in-class Exercise 7 with the `waiting_time.csv` dataset (available on  [cyberlearn](https://cyberlearn.hes-so.ch/mod/folder/view.php?id=721591)) by starting with a descriptive analysis. Here is the story. In a fast food, you rearrange the manufacturing process of several products and services. On paper, your reorganization is effective and reduces the waiting time. To check if this is true in practice, you compare the waiting time of customers (in seconds) between the start of the command and the final operation. There are two samples, one measured before the change, the other after. The changes will be maintained only if there is clear evidence of their effectiveness.

You will find the correction [here](https://samorso.github.io/RM2017/hmw_cor.html#ex4)
</div>

<div id="ex5">
**Exercise 5:** For a promotional campaign, a local airline company measures the impact on the increased ticket sales per dollar spent on four medias. The comapny wants to know whether there are differences between medias, and in particular which media has the best increase. To perform the analysis, use the `medias.csv` dataset available on  [cyberlearn](https://cyberlearn.hes-so.ch/mod/folder/view.php?id=721591).       
1. Load the dataset in `R`. First set the working directory (where you want to work with `R` in your computer) by using the `setwd("my directory")` commands. Then load the dataset using the command `media <- read.csv(file="medias.csv", header=TRUE, sep=";")`.   
2. Construct multiple boxplot and comment. In particular, how would you orientate the pairwise alternatives? Are there outliers?      
3. Perform a one-way ANOVA test by constructing the table. Give the working hypothesis. Inspire yourself from the in-class examples and conclude the test.       
4. Check your result by running the `R` command `aov(.)` (see the course for details).   
5. Run pairwise comparisons in `R` by applying the Dunn-Sidak correction, give full details.   
6. Do 4 and 5 using Kruskal-Wallis and Wilcoxon tests. Are there any contradictions? 

You will find the correction [here](https://samorso.github.io/RM2017/hmw_cor.html#ex5)
</div>

# Multivariate Regression model
<div id="ex6">
**Exercise 6:** Based on In-class Exercises 9 to 17, train yourself on the `Prestige` dataset from the `R` package `car` (first you need to install this package). Using all the material seen in class, you should be able to answer the following questions:  

* Is my regression a good fit?   
* Does all my assumptions hold?   
* Is there a problem of multicollinearity? Heteroscedasticity? Outliers? Non-linearity? Autocorrelation?  
* Should I include/exclude predictors?   
* ...
</div>
