---
title: "Multivariate statistics"
subtitle: "Homeworks - correction"
author: "Samuel Orso"
date: "`r Sys.Date()`"
output: 
 prettydoc::html_pretty:
  theme: architect
  highlight: github
  toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction: Multivariate regression
<div id="ex1">
**Exercise 1:** Will be revealed soon.
```{r,cache=TRUE,eval=TRUE,echo=FALSE,message=FALSE,warnings=FALSE,results='hide',fig.align='center',fig.height=4,fig.width=6,fig.show='hide'}
# to load the data
# data(women)

# see the dataset
# women

# read explanations about the dataset
# ?women

# 3. Plot
require(ggplot2)
ggplot(women, aes(x = height, y = weight)) + 
  geom_point()

# 5. Fit the regression
fit_lm <- lm(weight ~ height, data = women)

# 6. Summary
summary(fit_lm)

# 7. Change of unit using grid package (install it befor)
# install.package("grid")
require(grid)
new_x <- convertX(unit(173,"cm"),"inches")

# predict using R code, by hand is ok
predict(fit_lm,newdata = data.frame(height = as.numeric(new_x)))
```

<!-- 4. The regression equation is $$ \text{weight}_i = \beta_0 + \beta_1 \text{height}_i + \varepsilon_i,\quad i = 1,\dots,15.$$ -->

<!-- 6. The estimated regression equation is $$ \widehat{\text{weight}}_i = `r round(fit_lm$coefficients[1],2)` + `r round(fit_lm$coefficients[2],2)` \text{height}_i,\quad i = 1,\dots,15. $$ -->

<!-- 7. We simply replace the new *Height* in the estimated regression equation to obtain the predicted weight $\widehat{\text{weight}}^{\text{new}}$. The new *Height* needs to be changed to the right unit (from meters to inches). 173 cm is about `r round(as.numeric(new_x),2)` inches (see `R` code). We thus have $$ \widehat{\text{weight}}^{\text{new}} =  `r round(fit_lm$coefficients[1],2)` + `r round(fit_lm$coefficients[2],2)` \text{height}^{\text{new}} \approx `r round(round(fit_lm$coefficients[1],2) + round(fit_lm$coefficients[2],2) * round(as.numeric(new_x),2),2)`. $$ -->
</div>

# Descriptive analysis
<div id="ex2">
**Exercise 2** Will be revealed soon.
```{r,cache=TRUE,eval=TRUE,echo=FALSE,message=FALSE,warnings=FALSE,results='hide',fig.align='center',fig.height=4,fig.width=6,fig.show='hide'}
# 1.
# set the workind directoy (for me)
setwd("~/Documents/Teaching/RM/")

# to load the data
ski <- read.csv(file = "ski.csv", header = TRUE, sep = ";")

# see the dataset
head(ski)

# 2.
# load the ggplot2 package for plots
require(ggplot2)
require(gridExtra)
plot1 <- qplot(ski$Temperature, x=1, geom = "boxplot") + xlab(NULL) + coord_flip()
plot2 <- qplot(ski$Tickets, x=1, geom = "boxplot") + xlab(NULL) + coord_flip()
grid.arrange(plot1, plot2, ncol=1)

# 3.
ggplot(data = ski, aes(x = Temperature, y = Tickets)) + 
  geom_point() + 
  stat_smooth(method = "lm", col = "red")

# 4.
cor(ski)
cor(ski, method = "spearman")
# Both linear and correlation are very close numerically. It does not seem to have outliers. Also on the boxplots and scatterplot, no points seem to be outliers.

# 5. 
fit_lm <- lm(Tickets ~ Temperature, data = ski)
summary(fit_lm)

# 7.
predict(fit_lm, newdata = data.frame(Temperature = -2.5))
```

<!-- 6. The estimated regression equation is $$ \widehat{\text{Tickets}}_i = `r round(fit_lm$coefficients[1],2)` + `r round(fit_lm$coefficients[2],2)` \text{Temperature}_i,\quad i = 1,\dots,`r nrow(ski)`$$. -->

</div>

# Inference
<div id="ex3">
**Exercise 3:** Will be revealed soon.
```{r,cache=TRUE,eval=TRUE,echo=FALSE,message=FALSE,warnings=FALSE,results='hide'}
# set the workind directoy (for me)
setwd("~/Documents/Teaching/RM/")

# to load the data
hospital <- read.csv(file = "hospital.csv", header = TRUE, sep = ";")

# see the dataset
head(hospital)

# We need the average and the standard deviation
mean(hospital$Days)
sd(hospital$Days)

# We can also compute the quantiles (or use the tables)
qnorm(.975)
qnorm(.95)
qt(.975, df = 43)
qt(.95, df = 43)
```

<!-- 2. We have $\bar{x} = `r (mu <- round(mean(hospital$Days),4))`$ and the quantile $z_{0.975} = `r (z_a <- round(qnorm(.975),4))`$. The 95\% confidence interval is therefore $$ \text{CI}(\bar{x},95\%) = [`r mu` - `r z_a`/\sqrt{44};\; `r mu` + `r z_a`/\sqrt{44}] = [`r round(mu-z_a/sqrt(44),4)`;\;`r round(mu+z_a/sqrt(44),4)`] $$   -->
<!-- 3. The standard deviation is estimated at $\hat{\sigma}\approx `r (sig <- round(sd(hospital$Days),4))`$ and the quantile $t_{43;\;0.975} = `r (t_a <- round(qt(.975,df=43),4))`$. The 95\% confidence interval is therefore $$ \text{CI}(\bar{x},95\%) = [`r mu` - `r t_a`\;`r sig`/\sqrt{44};\; `r mu` + `r t_a`\;`r sig` /\sqrt{44}] = [`r round(mu-t_a*sig/sqrt(44),4)`;\;`r round(mu+t_a*sig/sqrt(44),4)`] $$   -->
<!-- 4. Clearly if the confidence level decreases, there is a lower probability that the confidence interval will contain the true value, it translates into a shorter interval. The quantiles are modifies as follows $z_{0.95} = `r (z_a <- round(qnorm(.95),4))`$ and $t_{43;\;0.95} = `r (t_a <- round(qt(.95,df=43),4))`$. The new confidence intervals are $$ \text{CI}(\bar{x},90\%) = [`r mu` - `r z_a`/\sqrt{44};\; `r mu` + `r z_a`/\sqrt{44}] = [`r round(mu-z_a/sqrt(44),4)`;\;`r round(mu+z_a/sqrt(44),4)`] $$ and  $$ \text{CI}(\bar{x},90\%) = [`r mu` - `r t_a`\;`r sig`/\sqrt{44};\; `r mu` + `r t_a`\;`r sig` /\sqrt{44}] = [`r round(mu-t_a*sig/sqrt(44),4)`;\;`r round(mu+t_a*sig/sqrt(44),4)`] $$   -->

</div>



# Multivariate Regression model
(coming soon)  

# Prediction
(coming soon)
