---
title: "Multivariate statistics"
subtitle: "In-class exercises"
author: "Samuel Orso"
date: "`r Sys.Date()`"
output: 
 prettydoc::html_pretty:
  theme: architect
  highlight: github
  toc: true
  df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Before we get started
<div id="ex1">
**Exercise 1:** Install `R` and `RStudio` on your personal laptop and reproduce the same code as in this subsection of the course.
</div>

# Introduction: Multivariate regression
<div id="ex2">
**Exercice 2:** Reproduce the same lines of code as **Example 1** on your laptop.
</div>

<div id="ex3">
**Exercice 3:** By helping yourself with the previous examples, explaine the *Price* (variable of interest) by the *Mileage* (predictor):   
1. Write the regression equation.   
2. Fit the regression using the `lm(.)` function.   
3. Using the `summary(.)` function, write the estimated regression equation.   
4. You observe a new car with mileage equals to 32500. Predict the price value.  
</div>

# Descriptive analysis
<div id="ex4">
**Exercise 4:** The dataset `marathon.csv` (on [cyberlearn](https://cyberlearn.hes-so.ch/mod/folder/view.php?id=721591)) contains a sample of time (minutes) at marathon of Boston [Keller].   
1. Load the dataset in `R`. First set the working directory (where you want to work with `R` in your computer) by using the `setwd("my directory")` commands. Then load the dataset using the command `marathon <- read.csv(file="marathon.csv", header=TRUE, sep=";")`.   
2. Compute the average, the standard deviation and the 5-number-summary.  
3. Make the boxplot of the data. What are the outliers?   
4. Build the histogram of the data. Describe the shape of the distribution? Determine approximately the mode of the distribution.   
</div>

<div id="ex5">
**Exercise 5:** The dataset `fastfood.csv` (on [cyberlearn](https://cyberlearn.hes-so.ch/mod/folder/view.php?id=721591)) contains measures of times in second of services at several drives.   
1. Load the dataset in `R`. First set the working directory (where you want to work with `R` in your computer) by using the `setwd("my directory")` commands. Then load the dataset using the command `fastfood <- read.csv(file="fastfood.csv", header=TRUE, sep=";")`.  
2. Produce a barplot illustrating the number of measures per drives.   
3. Produce a boxplot per drive.   
4. Produce a scatterplot between drives.  
5. Compute the linear and Spearman's correlations between the drives, use the function `cor(.)` and `cor( . , method = "spearman")`.   
</div>

# Inference
<div id="ex6">
**Exercise 6:** Reperform **Example 1**, but with the **CS** dataset when explaining the *Price* with the *Mileage* and a level of significance $\alpha=8\%$.   
1. You need to specify the testing hypothesis, compute $t_{\text{obs}}$, the $p$-value, $T(8\%)$ and the rejection region.  
2. Try to make a graph of the rejection region. You need to change `dnorm` to `dt` and use another argument: `args = list(df = ?)`, where `?` is the number of degrees of freedom.   
3. Conclude the test based on the rejection region.  
</div>

<div id="ex7">
**Exercise 7:** In a chain of supermarkets, you want to know if a product is enhanced when installed in front or in the middle. The data set of product sales (a soda) is in `sales.csv`. We consider that being in front is a privilege, which is applied to a product if there is clear evidence that this position improves sales.  
1. Load the dataset in `R`. First set the working directory (where you want to work with `R` in your computer) by using the `setwd("my directory")` commands. Then load the dataset using the command `sales <- read.csv(file="sales.csv", header=TRUE, sep=";")`.  
2. Which test should you pick? What are the null and alternative hypothesis?  
3. Make a test for two populations. Use directly the `R` function `t.test(.)` and inspire yourself from the course. What is your conclusion?   
4. Same as 3 but with a paired $t$-test. What am I assuming when making this test?   
5. Repeat 3 and 4 with the Wilcoxon's signed-rank test. Is the conclusion different? How can you check if there are outliers? Have you found any?   
</div>


<div id="ex8">  
**Exercise 8:** We are interested in the difference of delays of airplaines at NYC in 2013.   
1. Load the data from the package `nycflights13`. Install and call the package.    
2. The data you are interested is called `flights`, run the command `flights` and `?flights` to understand the data.    
3. Construct a boxplot of `arr_delay` agains `carrier`. You can find to which company the `carrier` refers to in `airlines` data (just enter `airlines` in `R`).    
4. Perform an one-way ANOVA test of `arr_delay` per `carrier`. What are the hypothesis? What is your conclusion?    
5. Perform multiple comparisons. What is the Dunn-Sidak correction? How many pairs? For which pair can you conclude the test?   
6. Restart 4 and 5 with Kruskal-Wallis and Wilcoxon tests? Are there contradictions? If yes, why?  
</div>

# Multivariate Regression model
(coming soon)  

# Prediction
(coming soon)
